---
- apt: pkg=lighttpd state=present

- template: src=lighttpd.conf dest=/etc/lighttpd/lighttpd.conf
 
- file: src=/etc/lighttpd/conf-available/15-fastcgi-php.conf dest=/etc/lighttpd/conf-enabled/15-fastcgi-php.conf state=link
