---
## Example for Ansible Pull
## by Raymii.org

- name: Ansible Example Pull Mode
  hosts: localhost
  user: root
  connection: local # or ssh or paramiko

  roles:
    - bootstrap
    - lighttpd
    - php-fpm
    - docker-ansible
